# Generated by Django 4.0.3 on 2022-04-08 08:02

from django.db import migrations
import qsessions.models


class Migration(migrations.Migration):

    dependencies = [
        ('qsessions', '0002_session_created_at'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
            ],
            options={
                'verbose_name': 'session',
                'verbose_name_plural': 'sessions',
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('qsessions.session',),
            managers=[
                ('objects', qsessions.models.SessionManager()),
            ],
        ),
    ]
