# Generated by Django 4.0.3 on 2022-04-11 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='core.apartment')),
            ],
            options={
                'verbose_name': 'Apartment image',
                'verbose_name_plural': 'Apartments images',
                'ordering': ['-id'],
            },
        ),
    ]
