# Generated by Django 4.0.3 on 2022-04-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_apartmentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='price_per_month',
            field=models.DecimalField(db_index=True, decimal_places=3, max_digits=11),
        ),
    ]
